=== axelarnetwork/axelar-configs/registry/schemas/evm-chain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "evm-chain schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^(?:\\.\\.\\/)+schemas\\/evm-chain\\.schema\\.json$"
    },
    "id": { "type": "integer" },
    "name": { "type": "string" },
    "network": { "type": "string" },
    "nativeCurrency": { "$ref": "#/definitions/nativeCurrency" },
    "rpcUrls": {
      "type": "array",
      "items": { "type": "string", "format": "uri" }
    },
    "blockExplorers": {
      "type": "array",
      "items": { "$ref": "#/definitions/blockExplorer" }
    },
    "testnet": { "type": "boolean" },
    "iconUrl": {
      "type": "string",
      "pattern": "\\/images\\/chains\\/([a-z\\-]+)\\.svg$",
      "description": "the icon for the chain, must be a relative path to a svg icon under /images/chains"
    },
    "deprecated": {
      "type": "boolean",
      "default": false,
      "description": "This chain is scheduled to be deprecated"
    }
  },
  "required": [
    "$schema",
    "id",
    "name",
    "network",
    "nativeCurrency",
    "rpcUrls",
    "iconUrl"
  ],
  "additionalProperties": false,
  "description": "an EVM compatible chain configuration",
  "definitions": {
    "blockExplorer": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "url": { "type": "string", "format": "uri" }
      },
      "required": ["name", "url"],
      "additionalProperties": false,
      "description": "a block explorer for the chain"
    },
    "nativeCurrency": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "symbol": { "type": "string", "minLength": 2, "maxLength": 6 },
        "decimals": { "type": "integer", "minimum": 0 },
        "iconUrl": {
          "type": "string",
          "pattern": "\\/images\\/tokens\\/([a-z\\-]+)\\.svg$",
          "description": "the icon for the currency, must be a relative path to a svg icon under /images/tokens"
        }
      },
      "required": ["name", "symbol", "decimals", "iconUrl"],
      "additionalProperties": false,
      "description": "the native currency for the chain"
    },
    "rpcUrls": {
      "type": "object",
      "properties": {
        "http": {
          "type": "array",
          "items": { "type": "string", "format": "uri" }
        },
        "webSocket": {
          "type": "array",
          "items": { "type": "string", "format": "uri" }
        }
      },
      "required": ["http"],
      "additionalProperties": false,
      "description": "the RPC endpoints for the chain"
    }
  }
}

=== axelarnetwork/axelar-configs/registry/mainnet/evm/flare.chain.json
{
  "$schema": "../../schemas/evm-chain.schema.json",
  "id": 14,
  "network": "flare",
  "name": "Flare",
  "nativeCurrency": {
    "name": "Flare",
    "symbol": "FLR",
    "decimals": 18,
    "iconUrl": "/images/tokens/flr.svg"
  },
  "rpcUrls": ["https://flare-api.flare.network/ext/C/rpc"],
  "blockExplorers": [
    {
      "name": "flare-explorer",
      "url": "https://flare-explorer.flare.network/"
    }
  ],
  "iconUrl": "/images/chains/flare.svg",
  "testnet": false
}

=== axelarnetwork/axelar-configs/registry/testnet/evm/coston2.chain.json
{
  "$schema": "../../schemas/evm-chain.schema.json",
  "id": 114,
  "network": "flare-testnet",
  "name": "Coston2",
  "nativeCurrency": {
    "name": "Coston2 FLR",
    "symbol": "C2FLR",
    "decimals": 18,
    "iconUrl": "/images/tokens/coston-two.svg"
  },
  "rpcUrls": ["https://coston2-api.flare.network/ext/C/rpc"],
  "blockExplorers": [
    {
      "name": "coston2-explorer",
      "url": "https://coston2-explorer.flare.network/"
    }
  ],
  "iconUrl": "/images/chains/coston-two.svg",
  "testnet": true
}

=== axelarnetwork/axelar-configs/registry/mainnet/evm/turkchain.chain.json
{
  "$schema": "../../schemas/evm-chain.schema.json",
  "id": 1919,
  "network": "turkchain",
  "name": "Turkchain",
  "nativeCurrency": {
    "name": "TC",
    "symbol": "TURK",
    "decimals": 18,
    "iconUrl": "/images/tokens/turk.svg"
  },
  "rpcUrls": ["https://rpc.turkscan.com"],
  "blockExplorers": [
    {
      "name": "Turkscan",
      "url": "https://turkscan.com"
    }
  ],
  "iconUrl": "/images/chains/turkchain.svg",
  "testnet": false
}
